# ~/.config/i3/status/themes/dracula.conf

general {
    output_format = "i3bar"
    markup = "pango"
    interval = 1
    colors = false
}

order += "cpu_usage"
order += "cpu_temperature 0"
order += "memory"
order += "disk /"
order += "disk /home"
order += "ethernet _first_"
# order += "wireless _first_"
# order += "battery all"
order += "volume master"
order += "tztime local"

cpu_usage {
    format = "<span foreground='#8be9fd'>󰍛  %usage</span>"
}

cpu_temperature 0 {
    format = "<span foreground='#ffb86c'>󰔏  %degrees°C</span>"
    max_threshold = 75
    path = "/sys/devices/platform/coretemp.0/hwmon/hwmon*/temp1_input"
}

memory {
    format = "<span foreground='#50fa7b'>󰘚  %used/%total (%percentage_used)</span>"
}

disk "/" {
    format = "<span foreground='#f1fa8c'>/:  %used/%total (%percentage_used)</span>"
}

disk "/home" {
    format = "<span foreground='#f1fa8c'>/home:  %used/%total (%percentage_used)</span>"
}

ethernet _first_ {
    format_up = "<span foreground='#ff79c6'>󰈀  %ip</span>"
    format_down = "<span foreground='#ff5555'>󰈀  down</span>"
}

# wireless _first_ {
#     format_up = "<span foreground='#ff79c6'>󰖩  %ip (%quality)</span>"
#     format_down = "<span foreground='#ff5555'>󰖩  down</span>"
# }

# battery all {
#     format = "<span foreground='#bd93f9'>%status  %percentage %remaining</span>"
#     format_down = "<span foreground='#ff5555'>No battery</span>"
#     status_chr = "󰂄"
#     status_bat = "󰁹"
#     status_unk = "󰂑"
#     status_full = "󰁹"
#     low_threshold = 20
#     threshold_type = percentage
# }

volume master {
    format = "<span foreground='#bd93f9'>󰕾  %volume</span>"
    format_muted = "<span foreground='#6272a4'>󰝟  MUTE</span>"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

tztime local {
    format = "<span foreground='#6272a4'>󰃭  %a %d %b   󱑒  %H:%M:%S  </span>"
}
