# ~/.config/i3/status/themes/dragon.conf

general {
    output_format = "i3bar"
    markup = "pango"
    interval = 1
    colors = false
}

order += "cpu_usage"
order += "cpu_temperature 0"
order += "memory"
order += "disk /"
order += "disk /home"
order += "ethernet _first_"
# order += "wireless _first_"
# order += "battery all"
order += "volume master"
order += "tztime local"

cpu_usage {
    format = "<span foreground='#8ba4b1'>󰍛  %usage</span>"
}

cpu_temperature 0 {
    format = "<span foreground='#c34043'>󰔏  %degrees°C</span>"
    max_threshold = 75
    path = "/sys/devices/platform/coretemp.0/hwmon/hwmon*/temp1_input"
}

memory {
    format = "<span foreground='#8a9a7b'>󰘚  %used/%total (%percentage_used)</span>"
}

disk "/" {
    format = "<span foreground='#c8c093'>/:  %used/%total (%percentage_used)</span>"
}

disk "/home" {
    format = "<span foreground='#c8c093'>/home:  %used/%total (%percentage_used)</span>"
}

ethernet _first_ {
    format_up = "<span foreground='#957fb8'>󰈀  %ip</span>"
    format_down = "<span foreground='#7e9cd8'>󰈀  down</span>"
}

# wireless _first_ {
#     format_up = "<span foreground='#957fb8'>󰖩  %ip (%quality)</span>"
#     format_down = "<span foreground='#7e9cd8'>󰖩  down</span>"
# }

# battery all {
#     format = "<span foreground='#8a9a7b'>%status  %percentage %remaining</span>"
#     format_down = "<span foreground='#7e9cd8'>No battery</span>"
#     status_chr = "󰂄"
#     status_bat = "󰁹"
#     status_unk = "󰂑"
#     status_full = "󰁹"
#     low_threshold = 20
#     threshold_type = percentage
# }

volume master {
    format = "<span foreground='#ffa066'>󰕾  %volume</span>"
    format_muted = "<span foreground='#2a2a37'>󰝟  MUTE</span>"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

tztime local {
    format = "<span foreground='#727169'>󰃭  %a %d %b   󱑒  %H:%M:%S  </span>"
}
