# ~/.config/i3/status/themes/gruvbox.conf

general {
    output_format = "i3bar"
    markup = "pango"
    interval = 1
    colors = false
}

order += "cpu_usage"
order += "cpu_temperature 0"
order += "memory"
order += "disk /"
order += "disk /home"
order += "ethernet _first_"
# order += "wireless _first_"
# order += "battery all"
order += "volume master"
order += "tztime local"

cpu_usage {
    format = "<span foreground='#458588'>󰍛  %usage</span>"
}

cpu_temperature 0 {
    format = "<span foreground='#d65d0e'>󰔏  %degrees°C</span>"
    max_threshold = 75
    path = "/sys/devices/platform/coretemp.0/hwmon/hwmon*/temp1_input"
}

memory {
    format = "<span foreground='#98971a'>󰘚  %used/%total (%percentage_used)</span>"
}

disk "/" {
    format = "<span foreground='#d79921'>/:  %used/%total (%percentage_used)</span>"
}

disk "/home" {
    format = "<span foreground='#d79921'>/home:  %used/%total (%percentage_used)</span>"
}

ethernet _first_ {
    format_up = "<span foreground='#689d6a'>󰈀  %ip</span>"
    format_down = "<span foreground='#fb4934'>󰈀  down</span>"
}

# wireless _first_ {
#     format_up = "<span foreground='#689d6a'>󰖩  %ip (%quality)</span>"
#     format_down = "<span foreground='#fb4934'>󰖩  down</span>"
# }

# battery all {
#     format = "<span foreground='#d3869b'>%status  %percentage %remaining</span>"
#     format_down = "<span foreground='#fb4934'>No battery</span>"
#     status_chr = "󰂄"
#     status_bat = "󰁹"
#     status_unk = "󰂑"
#     status_full = "󰁹"
#     low_threshold = 20
#     threshold_type = percentage
# }

volume master {
    format = "<span foreground='#b16286'>󰕾  %volume</span>"
    format_muted = "<span foreground='#928374'>󰝟  MUTE</span>"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

tztime local {
    format = "<span foreground='#ebdbb2'>󰃭  %a %d %b   󱑒  %H:%M:%S  </span>"
}
