# ~/.config/i3/status/themes/tokyo.conf

general {
    output_format = "i3bar"
    markup = "pango"
    interval = 1
    colors = false
}

order += "cpu_usage"
order += "cpu_temperature 0"
order += "memory"
order += "disk /"
order += "disk /home"
order += "ethernet _first_"
# order += "wireless _first_"
# order += "battery all"
order += "volume master"
order += "tztime local"

cpu_usage {
    format = "<span foreground='#7aa2f7'>󰍛  %usage</span>"
}

cpu_temperature 0 {
    format = "<span foreground='#ff9e64'>󰔏  %degrees°C</span>"
    max_threshold = 75
    path = "/sys/devices/platform/coretemp.0/hwmon/hwmon*/temp1_input"
}

memory {
    format = "<span foreground='#9ece6a'>󰘚  %used/%total (%percentage_used)</span>"
}

disk "/" {
    format = "<span foreground='#e0af68'>/:  %used/%total (%percentage_used)</span>"
}

disk "/home" {
    format = "<span foreground='#e0af68'>/home:  %used/%total (%percentage_used)</span>"
}

ethernet _first_ {
    format_up = "<span foreground='#7dcfff'>󰈀  %ip</span>"
    format_down = "<span foreground='#f7768e'>󰈀  down</span>"
}

# wireless _first_ {
#     format_up = "<span foreground='#7dcfff'>󰖩  %ip (%quality)</span>"
#     format_down = "<span foreground='#f7768e'>󰖩  down</span>"
# }

# battery all {
#     format = "<span foreground='#9ece6a'>%status  %percentage %remaining</span>"
#     format_down = "<span foreground='#f7768e'>No battery</span>"
#     status_chr = "󰂄"
#     status_bat = "󰁹"
#     status_unk = "󰂑"
#     status_full = "󰁹"
#     low_threshold = 20
#     threshold_type = percentage
# }

volume master {
    format = "<span foreground='#bb9af7'>󰕾  %volume</span>"
    format_muted = "<span foreground='#414868'>󰝟  MUTE</span>"
    device = "default"
    mixer = "Master"
    mixer_idx = 0
}

tztime local {
    format = "<span foreground='#565f89'>󰃭  %a %d %b   󱑒  %H:%M:%S  </span>"
}
