#################################
#       General Settings        #
#################################
backend = "glx";
xrender-sync-fence = true;
vsync = true;
use-damage = true;

#################################
#       Visual Depth            #
#################################
shadow = true;
shadow-radius = 18;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 0.40;
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Polybar'",
  "class_g ?= 'Notify-osd'",
  "_GTK_FRAME_EXTENTS@:c"
];

blur-background = true;
blur-method = "dual_kawase";
blur-strength = 6;
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

#################################
#       Geometry & Opacity      #
#################################
corner-radius = 0;

active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;

#################################
#       Fading (Disabled)       #
#################################
fading = false;
